force-app/main/default/objects/Order_Table__c/Order_Table__c.object-meta.xml
<CustomObject>
    <label>Order Table</label>
    <nameField>
        <label>Order Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Table__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders Table</relationshipLabel>
    <relationshipName>Orders_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Table__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product_Table__c</referenceTo>
    <relationshipLabel>Orders Table</relationshipLabel>
    <relationshipName>Orders_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Table__c/Product_Table__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Table__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <label>Units Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductOrderController.cls
/**
* Online shop cosmetics.
*
* <P>Buying the selected product.
*
* @author Irina Bogdanets
* @version 1.0
*/

public class ProductOrderController {

    public String OrderNotCreated = Label.Order_not_created;
    public String NoPurchaseMade = Label.No_purchase_made;
    public String PurchaseMade = Label.Purchase_made;

    public Contact customer { get;set; }
    public Id productId { get;set; }
    public Product_Table__c product { get;set; }
    public Order_Table__c order { get;set; }

    public ProductOrderController() {
        customer = new Contact();
        order = new Order_Table__c();
        productId = ApexPages.currentPage().getParameters().get('id');
        product = [
            SELECT Id, Name, Unit_Price__c, Units_Available__c
            FROM Product_Table__c
            WHERE Id = :productId
            LIMIT 1
        ];
    }

    public void buyProduct() {
        findContact();
        createOrderTable();
        updateUnitAvailableInProductTable();
        clearForm();
    }

    public void findContact() {
        Contact contact;
        Boolean existingContact;
        try {
            contact = [
                SELECT Id, firstName, lastName, email
                FROM Contact
                WHERE email = :customer.Email
                LIMIT 1
            ];
        } catch (System.QueryException queryError) {
        }
        existingContact = (
            contact != null && (
                contact.FirstName!=customer.FirstName || contact.LastName!=customer.LastName
            )
        );
        if (contact == null) {
            insert customer;
        } else if (existingContact) {
            customer.Id = contact.Id;
            update customer;
        } else {
            customer = contact;
        }
    }

    public void createOrderTable() {
        order.Product__c = productId;
        order.Order_Amount__c = order.Units__c * product.Unit_Price__c;
        order.Contact__c = customer.Id;
        try {
            insert order;
        } catch(DmlException dmlError) {
            ApexPages.addmessage(
                new ApexPages.message(
                    ApexPages.severity.ERROR, OrderNotCreated
                )
            );
        }
    }

    public void updateUnitAvailableInProductTable() {
        Decimal currentUnitsAvailable = product.Units_Available__c;
        product.Units_Available__c -= order.Units__c;
        if (product.Units_Available__c < 0 ||
            currentUnitsAvailable - product.Units_Available__c == 0) {
                ApexPages.addMessage(
                    new ApexPages.Message(
                        ApexPages.Severity.ERROR, NoPurchaseMade
                    )
                );
            } else {
                update product;
                ApexPages.addMessage(
                    new ApexPages.Message(
                        ApexPages.Severity.CONFIRM, PurchaseMade
                    )
                );
            }
    }

    public void clearForm() {
        customer = new Contact();
        order = new Order_Table__c();
    }

}