force-app/main/default/objects/Product_Table__c/Product_Table__c.object-meta.xml
<CustomObject>
    <label>Product Table</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Table__c/fields/Added_Date__c.field-meta.xml
<CustomField>
    <fullName>Added_Date__c</fullName>
    <label>Added Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Table__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <label>Units Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Table__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Products Table</relationshipLabel>
    <relationshipName>Products_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Period_End__c.field-meta.xml
<CustomField>
    <fullName>Period_End__c</fullName>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Period_Start__c</fullName>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DataForProductTable.cls
/**
* Data for testing online shop cosmetics.
*
* @author Irina Bogdanets
* @version 1.0
*/

@isTest
public class DataForProductTable {
    public static void createContact() {
        insert new Contact(
            email = 'irinabogdanets@gmail.com',
            firstName = 'Irina',
            lastName = 'Bogdanets'
        );
    }
    
    public static void createWarehouse() {
        insert new Warehouse__c(
            Name = 'Warehouse ' + String.valueOf(Date.today()) + ' ' +
                    String.valueOf(Date.today() + 5),
            Period_Start__c = Date.today(),
            Period_End__c = Date.today() + 5
        );
    }

    public static void createProduct() {
        insert new Product_Table__c(
            name = 'Lipstick',
            Added_Date__c = Date.today(),
            Unit_Price__c = 2,
            Units_Available__c = 10
        );
    }
    
}