force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/DateMatch__c.field-meta.xml
<CustomField>
    <fullName>DateMatch__c</fullName>
    <label>DateMatch</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/TeamOne__c.field-meta.xml
<CustomField>
    <fullName>TeamOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamOne</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/TeamTwo__c.field-meta.xml
<CustomField>
    <fullName>TeamTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamTwo</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (TeamTwo)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchManageTest.cls
@isTest
private class MatchManageTest {

    private static final String TEST_DATE = '05/05/2018';
    private static final String TEST_SUCCESS_RQUEST = '[{"MatchName" : "Name","MatchDate" : "2018-05-10","MatchTeamOne" : "Team3","MatchTeamTwo" : "Team4"}]';
    private static final String TEST_ERROR_RQUEST = '[{"MatchName" : "Name","MatchDate" : "2018-05-05","MatchTeamOne" : "Team1","MatchTeamTwo" : "Team3"}]';

    @testSetup
    private static void setup() {

        List<Team__c> teams = new List<Team__c>();
        Team__c team1 = new Team__c(
                Name = 'Team1'
            );
        teams.add(team1);
        Team__c team2 = new Team__c(
                Name = 'Team2'
            );
        teams.add(team2);
        insert teams;

        Match__c match = new Match__c(
            	Name = 'Match',
                DateMatch__c = Date.parse(TEST_DATE),
                TeamOne__c = team1.Id,
                TeamTwo__c = team2.Id
        );
        insert match;

    }

	@isTest
    private static void test_success_createMatches() {

        String success = Label.Success;

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Matches';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(TEST_SUCCESS_RQUEST);
        RestContext.request = request;

        Test.startTest();
        String result = MatchManage.createMatches();
        Test.stopTest();

		System.equals(result, success);

    }

    @isTest
    private static void test_error_createMatches() {

        String error = Label.ErrorREST;

        RestRequest request = new RestRequest();
        request.requestUri = '/services/apexrest/Matches';
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(TEST_ERROR_RQUEST);
        RestContext.request = request;

        Test.startTest();
        String result = MatchManage.createMatches();
        Test.stopTest();

		System.equals(result, error);

    }

}