force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/DateMatch__c.field-meta.xml
<CustomField>
    <fullName>DateMatch__c</fullName>
    <label>DateMatch</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/TeamOne__c.field-meta.xml
<CustomField>
    <fullName>TeamOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamOne</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/TeamTwo__c.field-meta.xml
<CustomField>
    <fullName>TeamTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TeamTwo</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (TeamTwo)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchController.cls
public without sharing class MatchController {
    
    @AuraEnabled
    public static List<Match__c> getRecordsWithPeriod(String dateStart, String dateEnd) {

        Date start = Date.valueOf(dateStart);
        Date finish = Date.valueOf(dateEnd);

        List<Match__c> matches = [
            SELECT Id, Name, DateMatch__c, TeamOne__c, TeamOne__r.Name, TeamTwo__c, TeamTwo__r.Name
            FROM Match__c
            WHERE DateMatch__c >= :start
            AND DateMatch__c <= :finish
        ];

        return matches;
    }
    
}